### ISSUE TITLE
Ubuntu Cosmic doesn't currently support cmake 3.13

### ISSUE THREAD

**Issue by drwl** [shuhaoliu/docker-clion-dev#1]
CMakeLists.txt has cmake version 3.13 as a dependency, but currently Cosmic supports 3.12.1-1

https://launchpad.net/ubuntu/cosmic/+source/cmake

**Comment by shuhaoliu** [comment]
Thanks, @drwl for pointing this out. @craftytrickster has fixed this problem in PR #3 .
